// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN4NA6RlzdB82B7L6_NeIy13XBkpIFZTM',
    appId: '1:708638746680:web:d498a48e9cf0af2a571ecd',
    messagingSenderId: '708638746680',
    projectId: 'e-commerce-flutter-6b956',
    authDomain: 'e-commerce-flutter-6b956.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-6b956.appspot.com',
    measurementId: 'G-B0GGCNVRZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuVbLsGa4pn0l4lp_ZjgVCVtMRhyLKAJk',
    appId: '1:708638746680:android:502b12d62456721f571ecd',
    messagingSenderId: '708638746680',
    projectId: 'e-commerce-flutter-6b956',
    storageBucket: 'e-commerce-flutter-6b956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeGtlM5loWiphhEB33bGEG8opDOSm3XSs',
    appId: '1:708638746680:ios:da7663bb898c8bfb571ecd',
    messagingSenderId: '708638746680',
    projectId: 'e-commerce-flutter-6b956',
    storageBucket: 'e-commerce-flutter-6b956.appspot.com',
    iosBundleId: 'com.example.eCommerceFlutter',
  );
}
